# Generated by Django 2.1.3 on 2018-12-02 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=34, unique=True)),
                ('added_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=11)),
                ('title', models.CharField(max_length=100)),
                ('added', models.DateTimeField()),
                ('removed', models.DateTimeField(null=True)),
                ('downloaded', models.DateTimeField(null=True)),
                ('do_not_download', models.BooleanField(default=False)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='playlists.Playlist')),
            ],
        ),
    ]
