# Generated by Django 2.1.3 on 2018-12-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='privated',
            field=models.BooleanField(default=False),
        ),
    ]
